version: 0.2

env:
  secrets-manager:
    D9TOKEN_PARAM: d9

phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - npm install
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the '__tests__' directory
      #- npm run test
      # Install the CloudGuard Workload CLI Plugin
      - npm install -g https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz
      # Set your AWS region variable
      - export AWS_REGION=us-east-1
      # Set Dome9 Token
      - echo $D9TOKEN_PARAM >> cloudguard-config.json
      # Remove all unit tests to reduce the size of the package that will be ultimately uploaded to Lambda
      - rm -rf ./__tests__
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      - npm prune --production
      # Set the S3 bucket name variable
      - export S3_BUCKET=rolop-cloudguard-bucket
  build:
    commands:
      # Configure the CloudGuard Workload Proact security on the SAM template
      - cat cloudguard-config.json
      - cloudguard proact -m template.yml
    
      # Add the FSP Runtime security to the deployed function
      - cloudguard fsp -C template.yml --region $AWS_REGION
      # creating the cloudformation stack template for the serverless app using the SAM template
      - aws cloudformation package --template template.protected.yml --s3-bucket $S3_BUCKET --output-template output.template.yml
      # Deploying the serverless app with the FSP using the cloudformation stack.
      - aws cloudformation deploy --template-file output.template.yml --stack-name awssampipe99 --capabilities CAPABILITY_IAM --parameter-overrides ServiceCount=1

artifacts:
  type: zip
  files:
    - output.template.yml
    - template.protected.yml
